4
sa10_reg_2_/D sa10_reg_2_/Q
Traceback (most recent call last):
  File "/home/jiajiexu/DT_ECO/MOSAC/DT_ECO.py", line 49, in <module>
    agent.train(
  File "/home/jiajiexu/DT_ECO/MOSAC/mosac_dicrete_action.py", line 504, in train
    next_obs, rewards, terminated, truncated, infos = self.env.step(actions)
                                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jiajiexu/anaconda3/lib/python3.11/site-packages/gymnasium/wrappers/order_enforcing.py", line 56, in step
    return self.env.step(action)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jiajiexu/anaconda3/lib/python3.11/site-packages/mo_gymnasium/envs/dt_eco/dt_eco.py", line 275, in step
    self._process_gate_features()
  File "/home/jiajiexu/anaconda3/lib/python3.11/site-packages/mo_gymnasium/envs/dt_eco/dt_eco.py", line 144, in _process_gate_features
    ef_index.append(self.graph.edge_ids(self.nodes[current_gate + '/' + inpin], self.nodes[current_gate + '/' + outpin], etype='cellarc'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jiajiexu/anaconda3/lib/python3.11/site-packages/dgl/heterograph.py", line 3264, in edge_ids
    raise DGLError(
dgl._ffi.base.DGLError: Error: (48777, 47516) does not form a valid edge.
